name: Package

on:
  push:
    branches: [ main ]

concurrency:
  group: package
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  package-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Maven
        id: cache-maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      
      - name: Cache JavaFX jmods
        id: cache-javafx
        uses: actions/cache@v4
        with:
          path: javafx-jmods-21.0.7
          key: ${{ runner.os }}-javafx-jmods-21.0.7
          restore-keys: |
            ${{ runner.os }}-javafx-jmods-21.0.7

      - name: Download JavaFX jmods
        run: |
          wget https://download2.gluonhq.com/openjfx/21.0.7/openjfx-21.0.7_linux-x64_bin-jmods.zip -O javafx-jmods.zip
          unzip javafx-jmods.zip -d javafx-jmods

      - name: Maven Build
        run: mvn --threads 4C clean package -DskipTests

      - name: jpackage
        run: |
          jpackage \
            --input target \
            --name JiraiboxSweeper \
            --main-jar jiraibox-sweeper-0.1.0-shaded.jar \
            --main-class com.yifen9.jiraiboxsweeper.Main \
            --type app-image \
            --icon src/main/resources/icon.png \
            --module-path "javafx-jmods/javafx-jmods-21.0.7" \
            --add-modules java.base,java.logging,javafx.base,javafx.graphics,javafx.controls,javafx.fxml,jdk.crypto.ec \
            --dest dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: dist/

  package-windows-msi:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      
      - name: Cache Maven
        id: cache-maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      
      - name: Cache JavaFX jmods
        id: cache-javafx
        uses: actions/cache@v4
        with:
          path: javafx-jmods-21.0.7
          key: ${{ runner.os }}-javafx-jmods-21.0.7
          restore-keys: |
            ${{ runner.os }}-javafx-jmods-21.0.7

      - name: Download JavaFX jmods
        run: |
          Invoke-WebRequest https://download2.gluonhq.com/openjfx/21.0.7/openjfx-21.0.7_windows-x64_bin-jmods.zip -OutFile javafx-jmods.zip
          Expand-Archive javafx-jmods.zip -DestinationPath javafx-jmods

      - name: Maven Build
        run: mvn --threads 4C clean package -DskipTests

      - name: jpackage
        run: |
          jpackage `
            --input target `
            --name JiraiboxSweeper `
            --main-jar jiraibox-sweeper-0.1.0-shaded.jar `
            --main-class com.yifen9.jiraiboxsweeper.Main `
            --type msi `
            --icon src/main/resources/icon.ico `
            --app-version 0.1.${{ github.run_number }} `
            --win-menu `
            --win-shortcut `
            --win-dir-chooser `
            --module-path "javafx-jmods/javafx-jmods-21.0.7" `
            --add-modules java.base,java.logging,javafx.base,javafx.graphics,javafx.controls,javafx.fxml,jdk.crypto.ec `
            --dest dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows_msi
          path: dist/
  
  package-windows-app-image:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      
      - name: Cache Maven
        id: cache-maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      
      - name: Cache JavaFX jmods
        id: cache-javafx
        uses: actions/cache@v4
        with:
          path: javafx-jmods-21.0.7
          key: ${{ runner.os }}-javafx-jmods-21.0.7
          restore-keys: |
            ${{ runner.os }}-javafx-jmods-21.0.7

      - name: Download JavaFX jmods
        run: |
          Invoke-WebRequest https://download2.gluonhq.com/openjfx/21.0.7/openjfx-21.0.7_windows-x64_bin-jmods.zip -OutFile javafx-jmods.zip
          Expand-Archive javafx-jmods.zip -DestinationPath javafx-jmods

      - name: Maven Build
        run: mvn --threads 4C clean package -DskipTests

      - name: jpackage
        run: |
          jpackage `
            --input target `
            --name JiraiboxSweeper `
            --main-jar jiraibox-sweeper-0.1.0-shaded.jar `
            --main-class com.yifen9.jiraiboxsweeper.Main `
            --type app-image `
            --icon src/main/resources/icon.ico `
            --app-version 0.1.${{ github.run_number }} `
            --module-path "javafx-jmods/javafx-jmods-21.0.7" `
            --add-modules java.base,java.logging,javafx.base,javafx.graphics,javafx.controls,javafx.fxml,jdk.crypto.ec `
            --dest dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows_app-image
          path: dist/
  
  release:
    runs-on: ubuntu-latest
    needs: [package-linux, package-windows-msi, package-windows-app-image]
    if: ${{ always() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux
          path: linux
      
      - name: Download Windows MSI Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows_msi
          path: windows_msi
      
      - name: Download Windows App-Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows_app-image
          path: windows_app-image
      
      - name: Push to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin release || true
          git checkout -B release
          git rm -rf . || true

          git add linux windows
          git commit -m "Release from ${{ github.sha }}"
          git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} release
    
  delete:
    needs:
      - release
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Delete Linux Artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: linux
      
      - name: Delete Windows Artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: windows