name: Build & Release

on:
  push:
    branches: [ main ]

jobs:
  package-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Download JavaFX SDK
      run: |
        wget https://download2.gluonhq.com/openjfx/21.0.7/openjfx-21.0.7_linux-x64_bin-jmods.zip -O javafx-jmods.zip
        unzip javafx-jmods.zip -d javafx-jmods

    - name: Build shaded JAR
      run: mvn clean package -DskipTests

    - name: Package native image
      run: |
        jpackage \
          --input target \
          --name JiraiBoxSweeper \
          --main-jar jiraibox-sweeper-0.1.0-shaded.jar \
          --main-class com.yifen9.jiraiboxsweeper.Main \
          --type app-image \
          --module-path "$JAVA_HOME/jmods:$(pwd)/javafx-jmods" \
          --add-modules java.base,javafx.base,javafx.graphics,javafx.controls,javafx.fxml \
          --dest dist
      # --icon src/main/resources/icon.png `

    - name: Prepare release branch
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        if git show-ref --quiet refs/heads/release; then
          git checkout release
        else
          git checkout --orphan release
        fi

        git rm -rf . || true

        cp -r dist/* .
        git add .
        git commit -m "Release from ${GITHUB_SHA::7} on main"
    - name: Push to release branch
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: release
        github_token: ${{ secrets.GITHUB_TOKEN }}
  package-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Download JavaFX SDK (Windows)
        run: |
          Invoke-WebRequest https://download2.gluonhq.com/openjfx/21.0.7/openjfx-21.0.7_windows-x64_bin-jmods.zip -OutFile javafx-jmods.zip
          Expand-Archive javafx-jmods.zip -DestinationPath javafx-jmods

      - name: Maven Build
        run: mvn clean package -DskipTests

      - name: jpackage for Windows
        run: |
          jpackage `
            --input target `
            --name JiraiBoxSweeper `
            --main-jar jiraibox-sweeper-0.1.0-shaded.jar `
            --main-class com.yifen9.jiraiboxsweeper.Main `
            --type exe `
            --module-path "$JAVA_HOME/jmods:$(pwd)/javafx-jmods" `
            --add-modules java.base,javafx.base,javafx.graphics,javafx.controls,javafx.fxml `
            --dest dist
        # --icon src/main/resources/icon.png `

      - name: Commit Windows artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout release
          git rm -rf . || true
          cp -r dist/* .
          git add .
          git commit -m "Release Windows build from ${{ github.sha }}"
      - name: Push Windows to release
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: release
          github_token: ${{ secrets.GITHUB_TOKEN }}